version: "3"

services:
  loconotion:
    build:
      context: ../loconotion
      dockerfile: ../github-personal-page/docker/Dockerfile
    image: loconotion:latest
    volumes:
      - ${LOCONOTION_LOCAL_DIST:-/tmp/}:/app/loconotion/dist
    restart: always